/**:
  ros__parameters:
    video_device: "/dev/v4l/by-id/usb-Intel_R__RealSense_TM__Depth_Camera_435i_Intel_R__RealSense_TM__Depth_Camera_435i_114123062393-video-index0"
    #image_width: 640
    #image_height: 480
    #framerate: 30.0
    #pixel_format: "yuyv"
    #image_raw:
      #ffmpeg:
        #encoder: "h264_nvmpi"
        #bit_rate: 2000000 # Set the bit rate for the encoder. A higher bit rate results in better video quality but larger file sizes, while a lower bit rate results in lower video quality but smaller file sizes.
        #gop_size: 20 # Set the Group of Pictures (GOP) size for the encoder. A smaller GOP size can improve error resilience but may increase file size, while a larger GOP size can reduce file size but may be less resilient to errors.
        #qmax: 20 # Set the maximum quantization parameter (Q) for the encoder. Lower values result in higher quality but larger file sizes, while higher values result in lower quality but smaller file sizes.
        #encoder_av_options: 'num_capture_buffers:4;profile:main;preset:ultrafast'
