# This config file is used by ros2_control
joint_state_broadcaster:
  ros__parameters:
    use_local_topics: true

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    dev_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
dev_arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity