# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm2_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm2_controller:
  ros__parameters:
    joints:
      - joint_turntable
      - joint_axis1
      - joint_axis2
      - joint_axis3
      - joint_axis4
      - joint_ender
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
