# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/JointGroupPositionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - link_1_joint
      - link1_link2
      - a4_rotation
      - a5_rotation
      - a6_rotation
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: true
    allow_partial_joints_goal: true
    allow_nonzero_velocity_at_trajectory_end: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

gripper_controller:
  ros__parameters:
    joints:
      - finger_left_joint
      - finger_right_joint
    command_interfaces:
      - position
